= JBoss Modules with EAP by Example
:toc: left
:toclevels: 4
:numbered:
:source-highlighter: coderay
:icons: font

A step-by-step walkthrough of some of the capabilies of JBoss Modules in Red Hat Enterprise Application Platform 6.4 (also applies to JBoss AS 7 and Wildfly 8+).

== Prerequisites

. JBoss EAP 6.4 is installed and configured to use standalone.xml (the default)
. Maven is installed, and configured to use the https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CONFIGURE_MAVEN.md#configure-maven-to-build-and-deploy-the-quickstarts[JBoss Quickstarts]
. Optionally, JBoss Developer Studio is installed

== Simple application with dependencies bundled

. Deploy the Helloworld quickstart

 $ cd helloworld
 $ mvn clean package jboss-as:deploy

. The Helloworld quickstart does not contain any dependencies on third-party libraries

TIP: TODO: verify with module logging

TIP: TODO: Bundle a dependency

== Application bundles jar that JBoss provides as module

The modular class loading in JBoss EAP means that most JARs included in the JBoss installation are not automatically added to the application's classpath. This section demonstrates that an application can include a JAR part of the JBoss installation and there will be no class conflicts.

. Add dependency to joda-time:1.6.2 (same as version included as JBoss module) with compile scope. This will include the jar in the war
+
[source,xml]
.pom.xml
----
<dependency>
    <groupId>joda-time</groupId>
    <artifactId>joda-time</artifactId>
    <version>1.6.2</version>
</dependency>
----

. Add code to the servlet to display the current month
+
[source,java]
.HelloWorldServlet.java
----
import java.util.Locale;
import org.joda.time.LocalDate;

    // ... snip ...

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setContentType("text/html");
        PrintWriter writer = resp.getWriter();
        writer.println(PAGE_HEADER);
        writer.println("<h1>" + helloService.createHelloMessage("World") + "</h1>");
        writer.println("Current month is: "+ getMonthText(new LocalDate()));
        writer.println(PAGE_FOOTER);
        writer.close();
    }
    
    public String getMonthText(LocalDate date) {
        return date.monthOfYear().getAsText(Locale.ENGLISH);
    }
}
----

. Test the application. The servlet should display the current month: http://localhost:8080/jboss-helloworld/HelloWorld

. Verify the jar exists in the war.

 $ mvn clean package
 $ ls target/jboss-helloworld/WEB-INF/lib/
 joda-time-1.6.2.jar
+
As you can see, even though JBoss contains a module for joda-time, JBoss uses the version included in the WAR since no dependency is declared on the static module.

TIP: TODO: probably want to see the module loader output here

== Application depends on module

. Change the scope of the joda-time maven dependency to `provided`.
+
[source,xml]
.pom.xml
----
<dependency>
    <groupId>joda-time</groupId>
    <artifactId>joda-time</artifactId>
    <version>1.6.2</version>
    <scope>provided</scope>
</dependency>
----

. Build and deploy the application. It should fail.
+
----
22:12:00,743 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-9) MSC000001: Failed to start service jboss.deployment.unit."jboss-helloworld.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."jboss-helloworld.war".POST_MODULE: JBAS018733: Failed to process phase POST_MODULE of deployment "jboss-helloworld.war"
...
Caused by: java.lang.ClassNotFoundException: org.joda.time.LocalDate from [Module "deployment.jboss-helloworld.war:main" from Service Module Loader]
----

. Add a `jboss-deployment-structure.xml` that specifies a dependency on the joda-time module.
+
[source,xml]
.src/main/webapp/WEB-INF/jboss-deployment-structure.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.2">
    <deployment>
        <dependencies>
            <module name="org.joda.time" />
        </dependencies>
    </deployment>
</jboss-deployment-structure>
----
+
[NOTE]
====
Joda time is an `unsupported` module. This is for demonstration purposes only. In production you should deploy and maintain your own module instead of depending on any private modules.

 19:55:04,222 WARN  [org.jboss.as.dependency.unsupported] (MSC service thread 1-2) JBAS015868: Deployment "deployment.jboss-helloworld.war" is using an unsupported module ("org.joda.time:main") which may be changed or removed in future versions without notice.
====
+
[TIP]
====
You can use the following commands to see which modules are marked public, private, or unsupported:

----
cd $JBOSS_HOME/modules/system/layers/base

# print private and unsupported modules
find . -name module.xml | xargs grep -l property | sort

# print public modules
find . -name module.xml | xargs grep -L property | sort
====

== Application depends on custom static module
Since joda-time is unsupported, we should deploy our own module--that we will maintain--and depend on it instead. In fact, it is a good practice to create and maintain any static modules you may need, so you can upgrade with less risk. This applies to most third-party modules. However, if an application depends on container-provided functionality, like JBoss Logging, it should depend on the JBoss-provided module.

. Let's upgrade our dependency on joda-time to the latest version (`2.4` at the time of this writing). That way we can use new features, such as `MonthDay`. Change the version of joda-time in the `pom.xml` to 2.4. Leave the scope as `provided`.
+
[source,xml]
.pom.xml
----
<dependency>
    <groupId>joda-time</groupId>
    <artifactId>joda-time</artifactId>
    <version>2.4</version>
    <scope>provided</scope>
</dependency>
----

. Create a method that uses the `MonthDay` class, and returns a `String` value that will be displayed.
+
[source,java]
.HelloWorldServlet.java
----
import java.util.Locale;
import org.joda.time.LocalDate;

    // ... snip ...

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setContentType("text/html");
        PrintWriter writer = resp.getWriter();
        writer.println(PAGE_HEADER);
        writer.println("<h1>" + helloService.createHelloMessage("World") + "</h1>");
        writer.println("Current month is: "+ getMonthText(new LocalDate()) + "<br>");
        writer.println("Abbreviation is: "+ getMonthShortText(new Date()));
        writer.println(PAGE_FOOTER);
        writer.close();
    }
    
    public String getMonthShortText(Date date) {
        return MonthDay.fromDateFields(date).monthOfYear().getAsShortText();
    }

    // ... snip ...
}
----

. Deploy the application and test. The application deploys, but a `ClassNotFoundException` is thrown:
+
----
java.lang.ClassNotFoundException: org.joda.time.MonthDay from [Module "deployment.jboss-helloworld.war:main" from Service Module Loader]
org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
----

. The application is still depending on the JBoss-provided joda-time module, which is an older version without the `MonthDay` class. There are two simple ways we can solve this problem:

.. Package the joda-time jar within the WAR, and remove the dependency on the container-provided module.
.. Create a custom static module and change the jboss-deployment-structure.xml to depend on that.

. Let's choose to create a custom static module. Create a directory for the module.
 
 $ mkdir -p $EAP_HOME/modules/org/joda/time/2.4

. Create a module.xml file.
+
[source,xml]
.$EAP_HOME/modules/org/joda/time/2.4/module.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.3" name="org.joda.time" slot="2.4">
    <resources>
        <resource-root path="joda-time-2.4.jar"/>
    </resources>
</module>
----

. Use Maven to resolve and copy the dependencies to the `target` folder, and copy `joda-time-2.4.jar` to the module directory.

 $ mvn dependency:copy-dependencies
 $ cp target/dependency/joda-time-2.4.jar $EAP_HOME/modules/org/joda/time/2.4/

. Update the `jboss-deployment-structure.xml` to use the correct module and slot.
+
[source,xml]
----
<dependencies>
    <module name="org.joda.time" slot="2.4" />
</dependencies>
----

. Deploy and test. The test is successful! Notice that no warnings were printed in the logs,

NOTE: We can choose any name for the module, slot, or directory within `modules`. By convention, we name the module similarly to the package or Maven coordinates. The slot name we use here is the version, since a main module for joda-time already exists (with the same name).

== Creating a dynamic module (JAR)

Static modules are good for creating common libraries that can be shared among multiple deployments--especially when those common libraries do not change often. But what if we have common libraries we want to make available but update almost as often as our application? Creating a dynamic module may be the right choice, since we can update it just like any other deployed artifact.

. Open the helloworld application. 

. Add a dependency on the common library: org.jboss.sample:common-utils:1.0. Set the scope to `provided`.

. Change the HelloService to use a function provided in the common-utils jar.

. If we were to deploy the jboss-helloworld.war right now it would fail, since the common-utils JAR is marked as provided and won't be included in the war. We need to create a dynamic module that the application can depend on. Let's start with a jboss-deployment-structure.xml for the application.
+
[source,xml]
.src/main/webapp/WEB-INF/jboss-deployment-structure.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.2">
    <deployment>
        <dependencies>
            <module name="deployment.common-utils-1.0.jar" />
        </dependencies>
    </deployment>
</jboss-deployment-structure>
----

. Deploy the application. It will fail, saying that a dependency is missing.
+
----
JBAS014775:    New missing/unsatisfied dependencies:
service jboss.module.service."deployment.jboss-helloworld.war".main (missing) dependents: [service jboss.deployment.unit."jboss-helloworld.war".FIRST_MODULE_USE] 

service jboss.module.spec.service."deployment.common-utils-1.0.jar".main (missing) dependents: [service jboss.module.resolve.phase."deployment.jboss-helloworld.war".main.1, service jboss.module.service."deployment.jboss-helloworld.war".main] 

service jboss.module.spec.service."deployment.jboss-helloworld.war".main (missing) dependents: [service jboss.module.service."deployment.jboss-helloworld.war".main]
----

. Let's deploy our common library. We can do this by using the JBoss CLI.
+
 $EAP_HOME/bin/jboss-cli.sh -c "deploy common-utils/target/common-utils-1.0.jar"

. Verify that the deployment was successful:
+
----
$EAP_HOME/bin/jboss-cli.sh -c deployment-info
NAME                 RUNTIME-NAME         PERSISTENT ENABLED STATUS               
common-utils-1.0.jar common-utils-1.0.jar true       true    OK   
----

. Deploy the jboss-helloworld.war and test. It will now be successful.

. Congratulations! You have created a dynamic module that is easy to maintain alongside your application.


== Creating an advanced dynamic module (EAR)

So we have seen how to create a dynamic module comprised of just a single JAR. But it is also possible to create a dynamic module comprised of multiple JARs, as well as one that depends on other modules. This can be useful if we have several JARs we want to expose to our application as a unit (create a module), that also will change often alongside our application (choose a dynamic module over static).

Let's pick up where we left off with the previous example. We have a WAR, jboss-helloworld.war, that depends on a dynamic module, common-utils-1.0.jar. The JAR is deployed by itself to JBoss EAP. The WAR contains a jboss-deployment-structure.xml that lists a dependency on the dynamic module named `deployment.common-utils-1.0.jar`.

First, we'll convert our dynamic module to use an EAR. This will allow us to add to the dynamic module in the following steps.

NOTE: You can also create dynamic modules with WAR files.

. Create an EAR project for the dynamic module named common-module. Include common-utils as a dependency.
+
[source,xml]
.pom.xml
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.jboss.sample</groupId>
    <artifactId>common-module</artifactId>
    <version>1.0</version>
    <packaging>ear</packaging>
    <name>common-module</name>

    <dependencies>
        <dependency>
            <groupId>org.jboss.sample</groupId>
            <artifactId>common-utils</artifactId>
            <version>1.0</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ear-plugin</artifactId>
                <version>2.8</version>
                <configuration>
                    <version>6</version>
                    <defaultLibBundleDir>lib</defaultLibBundleDir>
                    <fileNameMapping>no-version</fileNameMapping>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
----

. Build and deploy common-module-1.0.ear

. Modify the jboss-deployment-structure.xml of helloworld to point to the EAR
+
[source,xml]
.src/main/webapp/WEB-INF/jboss-deployment-structure.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.2">
    <deployment>
        <dependencies>
            <module name="deployment.common-module.ear" />
        </dependencies>
    </deployment>
</jboss-deployment-structure>
----
+
NOTE: Remember, if the `<finalName>` attribute is not specified in the EAR's pom.xml, the filename of the module will change each time the version changes. Consider using a `finalName` of `${project.artifactId}` for the ear to make new releases easier. Of course, there are benefits to knowing what the version of an artifact is at a glance.

. Build and deploy the helloworld application. The application works as expected. So far, packaging our dynamic module as an EAR is not providing any benefit. However that will change, as we will see next.

TIP: TODO: Include a second JAR in the module that is used by the application

TIP: TODO: Create a dependency for the module on a JAR in the EAR that is not used by the application

TIP: TODO: Create a dependency for the module on a JBoss static module that is not used by the application

== Advanced: Limiting class conflicts in EAR Subdeployments

Sometimes more control over the classpath is needed for subdeployments within an EAR (WARs or other JARs). This control can be attained by using the subdeployment elements of the jboss-deployment-structure.xml.

In this walkthrough we will see how to hide EAR/lib JARs that may be causing a conflict with a bundled WAR.

. We begin with an EAR that contains a WAR and some library JARs. The WAR depends on the common-utils.jar. The common-utils.jar depends on commons-lang3.jar for some operation.

. Build and deploy the ear file located at `ear-subdeployment/application-ear/target/application-ear.ear`.

 $ cd ear-subdeployment
 $ mvn clean package

. The servlet invokes a class in common-utils.jar to display the `Hello ::World::!` header. Below, a message shows that the `org.apache.commons.lang3.StringUtils` class was found on the classpath.

. For illustration purposes, let's decide that having the commons-lang StringUtils class visible to the WAR is undesirable. This can happen if class loading conflicts occur, such as ClassCastExceptions. There are many ways of solving this problem using JBoss Modules, but for this example, let's say both JARs must remain in the EAR's lib directory.

. To solve our class loading issue, we want to hide the commons-lang package from the WAR. To do this we create a jboss-deployment-structure.xml in the EAR's META-INF directory.
+
[source,xml]
./application-ear/src/main/application/META-INF/jboss-deployment-structure.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.2">
    <sub-deployment name="jboss-helloworld.war">
        
        <!-- By default, a dependency on the EAR's lib directory will be provided.
             The EAR parent module must be explicitly excluded, or our changes
             will have no effect.  -->
        <exclusions>
            <module name="deployment.application-ear.ear"/>
        </exclusions>
        
        <!-- We want to depend on the rest of the classes in the EAR's lib,
             so add a dependency on the EAR parent module, but exclude the class/package
             causing problems. -->
        <dependencies>
            <module name="deployment.application-ear.ear">
                <imports>
                    <exclude path="org/apache/commons/lang3"/>
                </imports>
            </module>
        </dependencies>
        
    </sub-deployment>
</jboss-deployment-structure>
----

. Build and deploy the application. Observe that the class search message now displays not found since the StringUtils was not found on the classpath of the WAR. However, the common-utils.jar was still able to invoke StringUtils to create the header.
